### ISSUE TITLE
how to remove subtitle?

### ISSUE THREAD

**Issue by talibnaik** [spchuang/videojs-caption#3]
Hi,
if subtitle are working on video then how to stop there?
there is not on and off button for this... how to handle this? nothing in your demo also...
guide please..

**Comment by spchuang** [comment]
You will like to hide the subtitle? Currently, there isn't a way to do it and I plan to add this functionality.

Meanwhile, you can have some hacky solution with css. You can temporarily hide the class "vjs-caption-overlay", which wraps all the caption text.

**Comment by talibnaik** [comment]
Yes have done it already. Thanks for this awesome plugin...Sent from Yahoo Mail for iPhoneAt 15-Jul-2015 1:53:37 am, spchuang wrote:You will like to hide the subtitle? Currently, there isn't a way to do it and I plan to add this functionality.

Meanwhile, you can have some hacky solution with css. You can temporarily hide the class "vjs-caption-overlay", which wraps all the caption text.
