### ISSUE TITLE
captions on Iphone fullscreen

### ISSUE THREAD

**Issue by philhenri** [spchuang/videojs-caption#8]
Hi

I tried your demo http://www.sampingchuang.com/videojs-caption on an iphone 6, and it goes full screen automatically when a video is player, but no caption is displayed (neither the source captions on the youtube TED video, neither your json captions)...

Can you help please?
thanks
philippe

**Comment by spchuang** [comment]
hi @philhenri, this plugin wouldn't work on mobile playbacks.
